services:
  platzi-market:
    image: platzi-market
    build: platzi-market
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://platziMarketDb:3306/platzi_market
      DB_USER: root
      DB_PASSWORD: 1234
    # networks: # Networks to join (Services on the same network can communicate with each other using their name)
    #   - platziMarketNetwork
    restart: always
    depends_on: 
      - platziMarketDb
  platziMarketDb:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: platzi_market
    # volumes:
    #   - ./platzi-market/dbscript.sql:/docker-entrypoint-initdb.d/dbscript.sql
    # networks: # Networks to join (Services on the same network can communicate with each other using their name)
    #   - platziMarketNetwork
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

# Volumes
# volumes:
#   db-data:

 # Networks to be created to facilitate communication between containers
networks:
  platziMarketNetwork:
    driver: bridge
